// <auto-generated />

using DatabaseLibrary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiApplication.Migrations
{
    [DbContext(typeof(PrisninjaDbContext))]
    [Migration("20220410143149_ProductStandardNames")]
    partial class ProductStandardNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.2.22153.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiApplication.Database.Models.Product", b =>
                {
                    b.Property<long>("EAN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EAN"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Organic")
                        .HasColumnType("bit");

                    b.Property<double>("Units")
                        .HasColumnType("float");

                    b.HasKey("EAN");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.ProductStandardName", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("MeasureG")
                        .HasColumnType("bit");

                    b.Property<bool>("MeasureL")
                        .HasColumnType("bit");

                    b.Property<bool>("MeasureStk")
                        .HasColumnType("bit");

                    b.Property<bool>("Organic")
                        .HasColumnType("bit");

                    b.Property<double>("StandardUnits")
                        .HasColumnType("float");

                    b.HasKey("Name");

                    b.ToTable("ProductStandardNames");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.ProductStore", b =>
                {
                    b.Property<long>("ProductKey")
                        .HasColumnType("bigint");

                    b.Property<int>("StoreKey")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductKey", "StoreKey");

                    b.HasIndex("StoreKey");

                    b.ToTable("ProductStores");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.Store", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Location_X")
                        .HasColumnType("float");

                    b.Property<double>("Location_Y")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.ProductStore", b =>
                {
                    b.HasOne("ApiApplication.Database.Models.Product", "Product")
                        .WithMany("ProductStores")
                        .HasForeignKey("ProductKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiApplication.Database.Models.Store", "Store")
                        .WithMany("ProductStores")
                        .HasForeignKey("StoreKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.Product", b =>
                {
                    b.Navigation("ProductStores");
                });

            modelBuilder.Entity("ApiApplication.Database.Models.Store", b =>
                {
                    b.Navigation("ProductStores");
                });
#pragma warning restore 612, 618
        }
    }
}
